<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Teste</title>
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h2>Teste</h2>
        <script src="" type="text/javascript"></script>
    </body>
</html>